### ISSUE TITLE
Create IconButton Component

### ISSUE THREAD

**Issue by dnmct** [devhausleipzig/camp-8-midterm-group-2#13]
## Steps

- [x] Create the component
- [x] Create a story for the component
- [x] Provide all the possible genre emojis

## Resources

- [Figma Component](https://www.figma.com/file/TOCJzJFMXE7PL1dQyGWqXZ/camp-8-midterm?node-id=193%3A51&t=l74D0T5C9RpowiD6-1)

**Comment by NoHara42** [comment]
@iameru finish
