### ISSUE TITLE
Create MovieCardsPagination Component

### ISSUE THREAD

**Issue by NoHara42** [devhausleipzig/camp-8-midterm-group-2#29]
For a response from `/movies/now_playing`, 
create a 4 card grid view with 2 cols and 2 rows.
Add a pagination navigation underneath the view, with a maximum of 5 views, each containing 4 cards.

https://www.figma.com/file/TOCJzJFMXE7PL1dQyGWqXZ/camp-8-midterm?node-id=226%3A211&t=1zm3EjK8aM4MZfWS-4

**Comment by iameru** [comment]
#36

**Comment by iameru** [comment]
requested review
