### ISSUE TITLE
Create Button Component

### ISSUE THREAD

**Issue by dnmct** [devhausleipzig/camp-8-midterm-group-2#4]
## Steps

- [x] Create a reusable Button Component according to the [design](https://www.figma.com/file/TOCJzJFMXE7PL1dQyGWqXZ/camp-8-midterm?node-id=0%3A1&t=esKyhjq165JUMGN8-1)
- [x] Create the according story in storybook

## Requirements

- [x] #1

## Hints

- Before you define your own `Props`, look into reusing the native button props to make your component more flexible

**Comment by amyria3** [comment]
donem ready for review
